##########################################################
#                    PaperMoney Config                   #
##########################################################
Prefix: "&b(&lPaperMoney&r&b)&r"

Enable_Money_Splitting: true
#Set this to true to allow players to turn larger bills into smaller bills
#THIS IS LITERALLY A PAPER DUPE. WARNING. THIS, BY DEFINITION, IS A PAPER DUPE.
#Enable this with care and don't say I didn't warn you.
#As added precaution, players also need the permission for splitting found
#    in the permission section below.

Min_Amount: 1
#This is used so players can't make paper money worth $0 and duplicate paper.

Maximum_Decimal_Places: 2
#This is to how many places past the decimal point currency can go
# $19.999 for example would be 3. Most real life currency doesn't go this far.
# $19.99 would be 2. This is where most real life currency goes.
# $19.9 would be 1. This is shorter than real life currency
# $1 would be 0. This limits money to whole numbers.

Use_Holograms_If_Possible: true
#Self explanatory

Sound: "NONE"
#Sounds can be found at 
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
#Caps matter

Disable_Right_Click_Deposit: false
#If this is set to true, paper notes are permanently kept in item form
#Use this if you want a TRULY immersive experience.
#I can't tell you how to handle distribution, that's on you.

Drop_All_On_Death: false
#If this is set to true, players will drop all their money when they die.

Item:
 id: PAPER
 amount: 1
# id: DIRT
# amount: 1
# enchantments:
#  - "arrowdamage:1"
#  - "arrowfire:1"
#  - "arrowinfinite:1"
#  - "arrowknockback:1"
#  - "damage:1"
#  - "digspeed:1"
#  - "durability:1"
#  - "fireaspect:1"
#  - "knockback:1"
#  - "lootbonusblock:1"
#  - "lootbonusmob:1"
#  - "luck:1"
#  - "protectionfall:1"
#  - "protectionfire:1"
#  - "silktouch:1"
# tags:
#  - "textureskull:SKINVALUE"
#  - "playerskull:PLAYERNAME"
#  - "vanilladurability:256"
#  - "unbreakable:true"
#  - "custommodeldata:1234567"
#  - "fakeenchant:true" //Adds enchant glow to item without any enchantments
# flags:
#  - "HIDE_ATTRIBUTES"
#  - "HIDE_DESTROYS"
#  - "HIDE_ENCHANTS"
#  - "HIDE_PLACED_ON"
#  - "HIDE_POTION_EFFECTS"
#  - "HIDE_UNBREAKABLE"
# attributes:
#  - "ATTRIBUTE:VALUE:OPERATION"
#  - "ATTRIBUTE:VALUE:OPERATION:SLOT"
#  - ATTRIBUTE NAMES FOUND @ https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/Attribute.html 
#  - ATTRIBUTE OPERATIONS FOUND @ https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/AttributeModifier.Operation.html
#  - ATTRIBUTE SLOTS FOUND @ https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/EquipmentSlot.html

Item_Name: "&a₱&6%pm_bill_worth%"
Item_Lore:
  - "&rA PaperMoney note."
  - "Made by: %player_displayname%"
  
#Syntax
# %pm_bill_worth% --> The amount that a bill is worth
# %pm_player_money% --> Player's money
# %pm_player_name% --> Player's name
# All PlaceholderAPI syntax is allowed.

##########################################################
#                       Permission                       #
##########################################################

# papermoney.make
#Allows players to run the /pmoney make command.

# papermoney.make.others
#Allows players to run the /pmoney make (playerName) command.

# papermoney.take
#Allows players to run the /pmoney take command.

# papermoney.take.others
#Allows players to run the /pmoney take (playerName) command.

# papermoney.reload
#Allows players to run the /pmoney reload command

# papermoney.split
#Allows players to run the /pmoney split command

##########################################################
#                        Version                         #
##########################################################

VERSION: 8
#Do not touch this. No touchy.