name: "PaperMoney"
author: TheTealViper
version: "1.18.2.a.5"
api-version: 1.16
description: "Physical money"
main: me.TheTealViper.papermoney.PaperMoney
depend: [Vault]
softdepend: [HolographicDisplays, DecentHolograms, PlaceholderAPI]
commands:
  papermoney:
    description: "Main command"
    aliases: [pmoney]