name: "PaperMoney"
author: TheTealViper
version: "1.20.4.a.1"
api-version: "1.19"
description: "Physical money"
main: me.TheTealViper.papermoney.PaperMoney
depend: [Vault]
softdepend: [HolographicDisplays, DecentHolograms, PlaceholderAPI]
commands:
  papermoney:
    description: "Main command"
    aliases: [pmoney]