name: "PaperMoney"
author: TheTealViper
version: "1.20.1.a.2"
api-version: "1.20"
description: "Physical money"
main: me.TheTealViper.papermoney.PaperMoney
depend: [Vault]
softdepend: [HolographicDisplays, DecentHolograms, PlaceholderAPI]
commands:
  papermoney:
    description: "Main command"
    aliases: [pmoney]