name: "PaperMoney"
author: TheTealViper
version: "1.18.1.b.7"
api-version: 1.16
description: "Physical money"
main: me.TheTealViper.papermoney.main
depend: [Vault]
softdepend: [HolographicDisplays]
commands:
  papermoney:
    description: "Main command"
    aliases: [pmoney]