name: "PaperMoney"
author: TheTealViper
version: "1.14.4.a.1"
api-version: 1.13
description: "Physical money"
main: me.TheTealViper.papermoney.main
depend: [Vault]
softdepend: [HolographicDisplays]
commands:
  papermoney:
    description: "Main command"
    aliases: [pmoney]